# Generated by Django 2.1.1 on 2018-11-01 02:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=50, verbose_name='Event Name')),
                ('Description', models.CharField(max_length=1000, verbose_name='Event Description')),
                ('Image', models.ImageField(upload_to='static/imagess')),
                ('Organiser1', models.CharField(max_length=50, verbose_name='Organisers1 Name')),
                ('Organiser2', models.CharField(max_length=50, verbose_name='Organisers2 Name')),
                ('Organiser3', models.CharField(max_length=50, verbose_name='Organisers3 Name')),
                ('MobileNo1', models.CharField(max_length=10, verbose_name="Organiser1's Mobile Number")),
                ('MobileNo2', models.CharField(max_length=10, verbose_name="Organiser2's Mobile Number")),
                ('MobileNo3', models.CharField(max_length=10, verbose_name="Organiser3's Mobile Number")),
                ('IsActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('EmailID', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('Comment', models.CharField(max_length=1000, verbose_name='Feedback....')),
            ],
        ),
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organized_by', models.CharField(max_length=10)),
                ('theme', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNo', models.CharField(blank=True, max_length=10, verbose_name="User's Mobile Number")),
                ('category', models.CharField(max_length=10)),
                ('usn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Student USN')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Title')),
                ('Content', models.CharField(max_length=1000, verbose_name='Content')),
                ('Image', models.ImageField(upload_to='static/imagess')),
                ('Category', models.CharField(max_length=50, verbose_name='Category')),
                ('CreatedBy', models.CharField(max_length=10, verbose_name='CreatedBy User ID')),
                ('CreatedOn', models.TimeField(default=datetime.datetime.now, editable=False)),
                ('UpdatedBy', models.CharField(max_length=10, null=True, verbose_name='UpdatedBy User ID')),
                ('UpdatedOn', models.DateField(null=True)),
                ('Priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.Events')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='FestName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.Fest'),
        ),
    ]
